import 'server-only'

import type {
  EmpresaDetail,
  EmpresaFuncionarioPedido,
  EmpresaSemanaPedidos,
} from '../types'

const DIAS_SEMANA_ATUAL = [
  { dia: '2026-08-03', diaSemanaLabel: 'Segunda-feira' },
  { dia: '2026-08-04', diaSemanaLabel: 'Terça-feira' },
  { dia: '2026-08-05', diaSemanaLabel: 'Quarta-feira' },
  { dia: '2026-08-06', diaSemanaLabel: 'Quinta-feira' },
  { dia: '2026-08-07', diaSemanaLabel: 'Sexta-feira' },
  { dia: '2026-08-08', diaSemanaLabel: 'Sábado' },
  { dia: '2026-08-09', diaSemanaLabel: 'Domingo' },
] as const

const FIM_DE_SEMANA_SEM_PEDIDO = [
  {
    ...DIAS_SEMANA_ATUAL[5],
    prato: null,
    tamanho: null,
    status: null,
    motivoErro: null,
  },
  {
    ...DIAS_SEMANA_ATUAL[6],
    prato: null,
    tamanho: null,
    status: null,
    motivoErro: null,
  },
] as const

const SEMANAS_ANTERIORES = [
  { semanaLabel: '27 jul – 02 ago', inicioSemana: '2026-07-27' },
  { semanaLabel: '20 jul – 26 jul', inicioSemana: '2026-07-20' },
  { semanaLabel: '13 jul – 19 jul', inicioSemana: '2026-07-13' },
]

const DIAS_LABEL = [
  'Segunda-feira',
  'Terça-feira',
  'Quarta-feira',
  'Quinta-feira',
  'Sexta-feira',
  'Sábado',
  'Domingo',
]

const PRATOS_HISTORICO = [
  'Frango grelhado',
  'Feijoada leve',
  'Estrogonofe de frango',
  'Filé de tilápia',
  'Salada Caesar',
]

const TAMANHOS_HISTORICO = ['P', 'M', 'G'] as const

// Gera um histórico de semanas anteriores determinístico (mesmo `seed` sempre
// produz o mesmo resultado), só pra popular a visão de histórico agrupado por
// semana enquanto não existe a tabela `pedido` real vinda do Drizzle.
function gerarHistoricoSemanas(seed: number): EmpresaSemanaPedidos[] {
  return SEMANAS_ANTERIORES.map((semana, semanaIndex) => {
    const inicio = new Date(`${semana.inicioSemana}T00:00:00`)

    const pedidos: EmpresaFuncionarioPedido[] = DIAS_LABEL.map(
      (diaSemanaLabel, diaIndex) => {
        const data = new Date(inicio)
        data.setDate(data.getDate() + diaIndex)
        const dia = data.toISOString().slice(0, 10)
        const rand = (seed * 31 + semanaIndex * 7 + diaIndex * 3) % 10
        const ehFimDeSemana = diaIndex >= 5

        if (ehFimDeSemana || rand < 2) {
          return {
            dia,
            diaSemanaLabel,
            prato: null,
            tamanho: null,
            status: null,
            motivoErro: null,
          }
        }

        return {
          dia,
          diaSemanaLabel,
          prato:
            PRATOS_HISTORICO[rand % PRATOS_HISTORICO.length] ??
            'Frango grelhado',
          tamanho: TAMANHOS_HISTORICO[rand % TAMANHOS_HISTORICO.length] ?? 'M',
          status: 'impresso',
          motivoErro: null,
        }
      }
    )

    return {
      semanaLabel: semana.semanaLabel,
      inicioSemana: semana.inicioSemana,
      pedidos,
    }
  })
}

export const EMPTY_DETAIL: EmpresaDetail = {
  status: 'ativo',
  endereco: {
    cep: '',
    logradouro: '',
    numero: '',
    bairro: '',
    cidade: '',
    uf: '',
  },
  pausas: [],
  funcionarios: [],
  envios: [],
  respostasSemanais: [],
  faturamentoMensal: [],
  documentos: [],
}

export const mockEmpresaDetails: Record<string, EmpresaDetail> = {
  '1': {
    status: 'ativo',
    endereco: {
      cep: '01310-200',
      logradouro: 'Avenida Paulista',
      numero: '1578',
      complemento: 'Andar 12',
      bairro: 'Bela Vista',
      cidade: 'São Paulo',
      uf: 'SP',
    },
    contrato: {
      valor: 18500,
      vigenciaInicio: '2026-01-01',
      vigenciaFim: '2026-12-31',
      prazoPagamento: 'Todo dia 10, mês seguinte',
      vigente: true,
    },
    documentos: [
      {
        id: 'd1',
        nome: 'Contrato assinado.pdf',
        tipo: 'contrato',
        arquivoUrl: '#',
        enviadoEm: '2026-01-01',
      },
      {
        id: 'd2',
        nome: 'Cartão CNPJ.pdf',
        tipo: 'outro',
        arquivoUrl: '#',
        enviadoEm: '2026-01-03',
      },
      {
        id: 'd3',
        nome: 'Termo de adesão.pdf',
        tipo: 'outro',
        arquivoUrl: '#',
        enviadoEm: '2026-01-05',
      },
    ],
    pausas: [
      { id: 'p1', data: '2026-04-21', motivo: 'Feriado municipal' },
      { id: 'p2', data: '2026-06-04', motivo: 'Manutenção do refeitório' },
      { id: 'p4', data: '2026-09-07', motivo: 'Feriado nacional' },
    ],
    funcionarios: [
      {
        id: 'f1',
        nome: 'Ana Beatriz Ferreira',
        setor: 'Obras',
        turno: 'Almoço',
        modalidade: 'marmita',
        vinculoStatus: 'ativo',
        respondeuEstaSemana: true,
        pedidoHoje: {
          ...DIAS_SEMANA_ATUAL[2],
          prato: 'Estrogonofe de frango',
          tamanho: 'M',
          status: 'impresso',
          motivoErro: null,
        },
        pedidosSemana: [
          {
            ...DIAS_SEMANA_ATUAL[0],
            prato: 'Frango grelhado',
            tamanho: 'M',
            status: 'impresso',
            motivoErro: null,
          },
          {
            ...DIAS_SEMANA_ATUAL[1],
            prato: 'Feijoada leve',
            tamanho: 'M',
            status: 'impresso',
            motivoErro: null,
          },
          {
            ...DIAS_SEMANA_ATUAL[2],
            prato: 'Estrogonofe de frango',
            tamanho: 'M',
            status: 'impresso',
            motivoErro: null,
          },
          {
            ...DIAS_SEMANA_ATUAL[3],
            prato: 'Filé de tilápia',
            tamanho: 'M',
            status: 'pendente',
            motivoErro: null,
          },
          {
            ...DIAS_SEMANA_ATUAL[4],
            prato: null,
            tamanho: null,
            status: null,
            motivoErro: null,
          },
          ...FIM_DE_SEMANA_SEM_PEDIDO,
        ],
        historicoSemanas: gerarHistoricoSemanas(1),
      },
      {
        id: 'f2',
        nome: 'Bruno Cesar Lima',
        setor: 'Obras',
        turno: 'Almoço',
        modalidade: 'marmita',
        vinculoStatus: 'ativo',
        respondeuEstaSemana: true,
        pedidoHoje: {
          ...DIAS_SEMANA_ATUAL[2],
          prato: 'Feijoada leve',
          tamanho: 'G',
          status: 'erro_impressao',
          motivoErro: 'Sem papel na impressora',
        },
        pedidosSemana: [
          {
            ...DIAS_SEMANA_ATUAL[0],
            prato: 'Frango grelhado',
            tamanho: 'G',
            status: 'impresso',
            motivoErro: null,
          },
          {
            ...DIAS_SEMANA_ATUAL[1],
            prato: 'Frango grelhado',
            tamanho: 'G',
            status: 'impresso',
            motivoErro: null,
          },
          {
            ...DIAS_SEMANA_ATUAL[2],
            prato: 'Feijoada leve',
            tamanho: 'G',
            status: 'erro_impressao',
            motivoErro: 'Impressora offline',
          },
          {
            ...DIAS_SEMANA_ATUAL[3],
            prato: 'Filé de tilápia',
            tamanho: 'G',
            status: 'pendente',
            motivoErro: null,
          },
          {
            ...DIAS_SEMANA_ATUAL[4],
            prato: 'Estrogonofe de frango',
            tamanho: 'G',
            status: 'pendente',
            motivoErro: null,
          },
          ...FIM_DE_SEMANA_SEM_PEDIDO,
        ],
        historicoSemanas: gerarHistoricoSemanas(2),
      },
      {
        id: 'f3',
        nome: 'Camila Ribeiro Alves',
        setor: 'Administrativo',
        turno: 'Almoço',
        modalidade: 'marmita',
        vinculoStatus: 'ativo',
        respondeuEstaSemana: false,
        pedidoHoje: null,
        pedidosSemana: [
          {
            ...DIAS_SEMANA_ATUAL[0],
            prato: 'Salada Caesar',
            tamanho: 'P',
            status: 'impresso',
            motivoErro: null,
          },
          {
            ...DIAS_SEMANA_ATUAL[1],
            prato: null,
            tamanho: null,
            status: null,
            motivoErro: null,
          },
          {
            ...DIAS_SEMANA_ATUAL[2],
            prato: null,
            tamanho: null,
            status: null,
            motivoErro: null,
          },
          {
            ...DIAS_SEMANA_ATUAL[3],
            prato: null,
            tamanho: null,
            status: null,
            motivoErro: null,
          },
          {
            ...DIAS_SEMANA_ATUAL[4],
            prato: null,
            tamanho: null,
            status: null,
            motivoErro: null,
          },
          ...FIM_DE_SEMANA_SEM_PEDIDO,
        ],
        historicoSemanas: gerarHistoricoSemanas(3),
      },
      {
        id: 'f4',
        nome: 'Diego Santos Pereira',
        setor: 'Administrativo',
        turno: 'Janta',
        modalidade: 'transport',
        vinculoStatus: 'inativo',
        respondeuEstaSemana: false,
        pedidoHoje: null,
        pedidosSemana: [],
        historicoSemanas: [],
      },
      {
        id: 'f9',
        nome: 'Erika Nascimento Costa',
        setor: 'Obras',
        turno: 'Almoço',
        modalidade: 'marmita',
        vinculoStatus: 'ativo',
        respondeuEstaSemana: false,
        pedidoHoje: {
          ...DIAS_SEMANA_ATUAL[2],
          prato: 'Filé de tilápia',
          tamanho: 'P',
          status: 'pendente',
          motivoErro: null,
        },
        pedidosSemana: [
          {
            ...DIAS_SEMANA_ATUAL[0],
            prato: null,
            tamanho: null,
            status: null,
            motivoErro: null,
          },
          {
            ...DIAS_SEMANA_ATUAL[1],
            prato: 'Frango grelhado',
            tamanho: 'P',
            status: 'impresso',
            motivoErro: null,
          },
          {
            ...DIAS_SEMANA_ATUAL[2],
            prato: 'Filé de tilápia',
            tamanho: 'P',
            status: 'pendente',
            motivoErro: null,
          },
          {
            ...DIAS_SEMANA_ATUAL[3],
            prato: null,
            tamanho: null,
            status: null,
            motivoErro: null,
          },
          {
            ...DIAS_SEMANA_ATUAL[4],
            prato: null,
            tamanho: null,
            status: null,
            motivoErro: null,
          },
          ...FIM_DE_SEMANA_SEM_PEDIDO,
        ],
        historicoSemanas: gerarHistoricoSemanas(5),
      },
      {
        id: 'f10',
        nome: 'Fábio Henrique Duarte',
        setor: 'Obras',
        turno: 'Janta',
        modalidade: 'marmita',
        vinculoStatus: 'ativo',
        respondeuEstaSemana: false,
        pedidoHoje: {
          ...DIAS_SEMANA_ATUAL[2],
          prato: 'Estrogonofe de frango',
          tamanho: 'G',
          status: 'pendente',
          motivoErro: null,
        },
        pedidosSemana: [
          {
            ...DIAS_SEMANA_ATUAL[0],
            prato: 'Feijoada leve',
            tamanho: 'G',
            status: 'impresso',
            motivoErro: null,
          },
          {
            ...DIAS_SEMANA_ATUAL[1],
            prato: 'Feijoada leve',
            tamanho: 'G',
            status: 'impresso',
            motivoErro: null,
          },
          {
            ...DIAS_SEMANA_ATUAL[2],
            prato: 'Estrogonofe de frango',
            tamanho: 'G',
            status: 'pendente',
            motivoErro: null,
          },
          {
            ...DIAS_SEMANA_ATUAL[3],
            prato: 'Estrogonofe de frango',
            tamanho: 'G',
            status: 'pendente',
            motivoErro: null,
          },
          {
            ...DIAS_SEMANA_ATUAL[4],
            prato: null,
            tamanho: null,
            status: null,
            motivoErro: null,
          },
          ...FIM_DE_SEMANA_SEM_PEDIDO,
        ],
        historicoSemanas: gerarHistoricoSemanas(6),
      },
      {
        id: 'f11',
        nome: 'Gabriela Moura Tavares',
        setor: 'Administrativo',
        turno: 'Almoço',
        modalidade: 'marmita',
        vinculoStatus: 'ativo',
        respondeuEstaSemana: false,
        pedidoHoje: null,
        pedidosSemana: [
          {
            ...DIAS_SEMANA_ATUAL[0],
            prato: null,
            tamanho: null,
            status: null,
            motivoErro: null,
          },
          {
            ...DIAS_SEMANA_ATUAL[1],
            prato: null,
            tamanho: null,
            status: null,
            motivoErro: null,
          },
          {
            ...DIAS_SEMANA_ATUAL[2],
            prato: null,
            tamanho: null,
            status: null,
            motivoErro: null,
          },
          {
            ...DIAS_SEMANA_ATUAL[3],
            prato: 'Salada Caesar',
            tamanho: 'P',
            status: 'pendente',
            motivoErro: null,
          },
          {
            ...DIAS_SEMANA_ATUAL[4],
            prato: null,
            tamanho: null,
            status: null,
            motivoErro: null,
          },
          ...FIM_DE_SEMANA_SEM_PEDIDO,
        ],
        historicoSemanas: gerarHistoricoSemanas(7),
      },
    ],
    envios: [
      {
        id: 'e1',
        data: '2026-02-09',
        horario: '11:42',
        status: 'erro',
        notaFiscalNumero: null,
        notaFiscalEmitidaEm: null,
        responsavel: 'Rafael Souza',
        motivoErro: 'Falha de conexão com a Consumer',
      },
      {
        id: 'e2',
        data: '2026-03-16',
        horario: '11:15',
        status: 'confirmado',
        notaFiscalNumero: '000098',
        notaFiscalEmitidaEm: '2026-03-16',
        responsavel: 'Juliana Prado',
        motivoErro: null,
      },
      {
        id: 'e3',
        data: '2026-03-24',
        horario: '11:38',
        status: 'erro',
        notaFiscalNumero: null,
        notaFiscalEmitidaEm: null,
        responsavel: 'Marcos Vieira',
        motivoErro: 'CNPJ divergente no cadastro',
      },
      {
        id: 'e9',
        data: '2026-04-13',
        horario: '11:20',
        status: 'confirmado',
        notaFiscalNumero: '000112',
        notaFiscalEmitidaEm: '2026-04-13',
        responsavel: 'Rafael Souza',
        motivoErro: null,
      },
      {
        id: 'e10',
        data: '2026-05-06',
        horario: '12:03',
        status: 'erro',
        notaFiscalNumero: null,
        notaFiscalEmitidaEm: null,
        responsavel: 'Juliana Prado',
        motivoErro: 'Nota fiscal rejeitada pela Sefaz',
      },
      {
        id: 'e11',
        data: '2026-06-18',
        horario: '11:55',
        status: 'erro',
        notaFiscalNumero: null,
        notaFiscalEmitidaEm: null,
        responsavel: 'Marcos Vieira',
        motivoErro: 'Tempo limite excedido',
      },
      {
        id: 'e12',
        data: '2026-07-02',
        horario: '11:10',
        status: 'confirmado',
        notaFiscalNumero: '000120',
        notaFiscalEmitidaEm: '2026-07-02',
        responsavel: 'Rafael Souza',
        motivoErro: null,
      },
      {
        id: 'e1b',
        data: '2026-07-27',
        horario: '11:18',
        status: 'confirmado',
        notaFiscalNumero: '000123',
        notaFiscalEmitidaEm: '2026-07-27',
        responsavel: 'Juliana Prado',
        motivoErro: null,
      },
      {
        id: 'e2b',
        data: '2026-07-28',
        horario: '11:22',
        status: 'confirmado',
        notaFiscalNumero: '000131',
        notaFiscalEmitidaEm: '2026-07-28',
        responsavel: 'Rafael Souza',
        motivoErro: null,
      },
      {
        id: 'e3b',
        data: '2026-07-29',
        horario: '11:47',
        status: 'erro',
        notaFiscalNumero: null,
        notaFiscalEmitidaEm: null,
        responsavel: 'Marcos Vieira',
        motivoErro: 'Falha de conexão com a Consumer',
      },
      {
        id: 'e4',
        data: '2026-07-30',
        horario: '11:12',
        status: 'confirmado',
        notaFiscalNumero: '000148',
        notaFiscalEmitidaEm: '2026-07-30',
        responsavel: 'Juliana Prado',
        motivoErro: null,
      },
      {
        id: 'e5',
        data: '2026-07-31',
        horario: '11:09',
        status: 'enviado',
        notaFiscalNumero: null,
        notaFiscalEmitidaEm: null,
        responsavel: 'Rafael Souza',
        motivoErro: null,
      },
      {
        id: 'e13',
        data: '2026-08-05',
        horario: '11:24',
        status: 'enviado',
        notaFiscalNumero: null,
        notaFiscalEmitidaEm: null,
        responsavel: 'Juliana Prado',
        motivoErro: null,
      },
    ],
    respostasSemanais: [
      { dia: 'Dom', responderam: 6, pendentes: 2 },
      { dia: 'Seg', responderam: 34, pendentes: 8 },
      { dia: 'Ter', responderam: 37, pendentes: 5 },
      { dia: 'Qua', responderam: 30, pendentes: 12 },
      { dia: 'Qui', responderam: 36, pendentes: 6 },
      { dia: 'Sex', responderam: 31, pendentes: 11 },
      { dia: 'Sáb', responderam: 9, pendentes: 3 },
    ],
    satisfacao: {
      media: 4.4,
      totalAvaliacoes: 87,
      categoriasFuncionarios: [
        { categoria: 'Sabor', media: 4.6, delta: 0.2 },
        { categoria: 'Temperos', media: 4.3, delta: -0.1 },
        { categoria: 'Variedade', media: 4.0, delta: 0.3 },
        { categoria: 'Quantidade', media: 4.5, delta: 0 },
        { categoria: 'Temperatura', media: 4.1, delta: -0.2 },
      ],
      categoriasEmpresa: [
        { categoria: 'Pontualidade', media: 4.5, delta: 0.1 },
        { categoria: 'Embalagem', media: 4.2, delta: -0.3 },
        { categoria: 'Atendimento', media: 4.7, delta: 0.2 },
      ],
    },
    faturamentoMensal: [
      { mes: 'Mar', valor: 15200 },
      { mes: 'Abr', valor: 16800 },
      { mes: 'Mai', valor: 17650 },
      { mes: 'Jun', valor: 18100 },
      { mes: 'Jul', valor: 18500 },
      { mes: 'Ago', valor: 18500 },
    ],
    comparativoSemanaAnterior: {
      funcionariosAtivos: 3,
      pedidosEnviados: 4,
      taxaResposta: 74,
    },
  },
  '2': {
    status: 'ativo',
    endereco: {
      cep: '04543-000',
      logradouro: 'Rua Funchal',
      numero: '263',
      bairro: 'Vila Olímpia',
      cidade: 'São Paulo',
      uf: 'SP',
    },
    contrato: {
      valor: 6200,
      vigenciaInicio: '2026-03-02',
      vigenciaFim: '2027-03-01',
      prazoPagamento: 'Todo dia 5, mês seguinte',
      vigente: true,
    },
    documentos: [
      {
        id: 'd4',
        nome: 'Contrato assinado.pdf',
        tipo: 'contrato',
        arquivoUrl: '#',
        enviadoEm: '2026-03-02',
      },
      {
        id: 'd5',
        nome: 'Comprovante de endereço.pdf',
        tipo: 'outro',
        arquivoUrl: '#',
        enviadoEm: '2026-03-04',
      },
    ],
    pausas: [],
    funcionarios: [
      {
        id: 'f5',
        nome: 'Eduarda Martins Souza',
        setor: 'Desenvolvimento',
        turno: 'Almoço',
        modalidade: 'marmita',
        vinculoStatus: 'ativo',
        respondeuEstaSemana: true,
        pedidoHoje: {
          ...DIAS_SEMANA_ATUAL[2],
          prato: 'Frango grelhado',
          tamanho: 'M',
          status: 'impresso',
          motivoErro: null,
        },
        pedidosSemana: [
          {
            ...DIAS_SEMANA_ATUAL[0],
            prato: 'Frango grelhado',
            tamanho: 'M',
            status: 'impresso',
            motivoErro: null,
          },
          {
            ...DIAS_SEMANA_ATUAL[1],
            prato: 'Feijoada leve',
            tamanho: 'M',
            status: 'impresso',
            motivoErro: null,
          },
          {
            ...DIAS_SEMANA_ATUAL[2],
            prato: 'Frango grelhado',
            tamanho: 'M',
            status: 'impresso',
            motivoErro: null,
          },
          {
            ...DIAS_SEMANA_ATUAL[3],
            prato: 'Estrogonofe de frango',
            tamanho: 'M',
            status: 'pendente',
            motivoErro: null,
          },
          {
            ...DIAS_SEMANA_ATUAL[4],
            prato: 'Filé de tilápia',
            tamanho: 'M',
            status: 'pendente',
            motivoErro: null,
          },
          ...FIM_DE_SEMANA_SEM_PEDIDO,
        ],
        historicoSemanas: gerarHistoricoSemanas(8),
      },
      {
        id: 'f6',
        nome: 'Felipe Augusto Rocha',
        setor: 'Desenvolvimento',
        turno: 'Almoço',
        modalidade: 'marmita',
        vinculoStatus: 'ativo',
        respondeuEstaSemana: false,
        pedidoHoje: {
          ...DIAS_SEMANA_ATUAL[2],
          prato: 'Feijoada leve',
          tamanho: 'M',
          status: 'erro_impressao',
          motivoErro: 'Falha de conexão com a impressora',
        },
        pedidosSemana: [
          {
            ...DIAS_SEMANA_ATUAL[0],
            prato: null,
            tamanho: null,
            status: null,
            motivoErro: null,
          },
          {
            ...DIAS_SEMANA_ATUAL[1],
            prato: null,
            tamanho: null,
            status: null,
            motivoErro: null,
          },
          {
            ...DIAS_SEMANA_ATUAL[2],
            prato: 'Feijoada leve',
            tamanho: 'M',
            status: 'erro_impressao',
            motivoErro: 'Sem papel na impressora',
          },
          {
            ...DIAS_SEMANA_ATUAL[3],
            prato: null,
            tamanho: null,
            status: null,
            motivoErro: null,
          },
          {
            ...DIAS_SEMANA_ATUAL[4],
            prato: null,
            tamanho: null,
            status: null,
            motivoErro: null,
          },
          ...FIM_DE_SEMANA_SEM_PEDIDO,
        ],
        historicoSemanas: gerarHistoricoSemanas(9),
      },
      {
        id: 'f12',
        nome: 'Helena Barbosa Cunha',
        setor: 'Desenvolvimento',
        turno: 'Almoço',
        modalidade: 'marmita',
        vinculoStatus: 'ativo',
        respondeuEstaSemana: false,
        pedidoHoje: null,
        pedidosSemana: [
          {
            ...DIAS_SEMANA_ATUAL[0],
            prato: 'Salada Caesar',
            tamanho: 'P',
            status: 'impresso',
            motivoErro: null,
          },
          {
            ...DIAS_SEMANA_ATUAL[1],
            prato: 'Salada Caesar',
            tamanho: 'P',
            status: 'impresso',
            motivoErro: null,
          },
          {
            ...DIAS_SEMANA_ATUAL[2],
            prato: null,
            tamanho: null,
            status: null,
            motivoErro: null,
          },
          {
            ...DIAS_SEMANA_ATUAL[3],
            prato: null,
            tamanho: null,
            status: null,
            motivoErro: null,
          },
          {
            ...DIAS_SEMANA_ATUAL[4],
            prato: null,
            tamanho: null,
            status: null,
            motivoErro: null,
          },
          ...FIM_DE_SEMANA_SEM_PEDIDO,
        ],
        historicoSemanas: gerarHistoricoSemanas(10),
      },
    ],
    envios: [
      {
        id: 'e6a',
        data: '2026-03-11',
        horario: '12:14',
        status: 'erro',
        notaFiscalNumero: null,
        notaFiscalEmitidaEm: null,
        responsavel: 'Marcos Vieira',
        motivoErro: 'Empresa sem contrato ativo na data',
      },
      {
        id: 'e6b',
        data: '2026-05-20',
        horario: '12:05',
        status: 'erro',
        notaFiscalNumero: null,
        notaFiscalEmitidaEm: null,
        responsavel: 'Rafael Souza',
        motivoErro: 'Nota fiscal rejeitada pela Sefaz',
      },
      {
        id: 'e6',
        data: '2026-07-29',
        horario: '12:20',
        status: 'confirmado',
        notaFiscalNumero: '000210',
        notaFiscalEmitidaEm: '2026-07-29',
        responsavel: 'Juliana Prado',
        motivoErro: null,
      },
      {
        id: 'e7',
        data: '2026-07-30',
        horario: '12:11',
        status: 'confirmado',
        notaFiscalNumero: '000217',
        notaFiscalEmitidaEm: '2026-07-30',
        responsavel: 'Juliana Prado',
        motivoErro: null,
      },
      {
        id: 'e14',
        data: '2026-08-05',
        horario: '12:02',
        status: 'enviado',
        notaFiscalNumero: null,
        notaFiscalEmitidaEm: null,
        responsavel: 'Marcos Vieira',
        motivoErro: null,
      },
    ],
    respostasSemanais: [
      { dia: 'Dom', responderam: 1, pendentes: 0 },
      { dia: 'Seg', responderam: 8, pendentes: 1 },
      { dia: 'Ter', responderam: 9, pendentes: 0 },
      { dia: 'Qua', responderam: 7, pendentes: 2 },
      { dia: 'Qui', responderam: 9, pendentes: 0 },
      { dia: 'Sex', responderam: 6, pendentes: 3 },
      { dia: 'Sáb', responderam: 2, pendentes: 0 },
    ],
    satisfacao: {
      media: 4.7,
      totalAvaliacoes: 15,
      categoriasFuncionarios: [
        { categoria: 'Sabor', media: 4.8, delta: 0.1 },
        { categoria: 'Temperos', media: 4.6, delta: 0.2 },
        { categoria: 'Variedade', media: 4.5, delta: 0 },
        { categoria: 'Quantidade', media: 4.9, delta: 0.1 },
        { categoria: 'Temperatura', media: 4.6, delta: -0.1 },
      ],
      categoriasEmpresa: [
        { categoria: 'Pontualidade', media: 4.9, delta: 0.1 },
        { categoria: 'Embalagem', media: 4.7, delta: 0 },
        { categoria: 'Atendimento', media: 4.7, delta: 0.2 },
      ],
    },
    faturamentoMensal: [
      { mes: 'Mai', valor: 5800 },
      { mes: 'Jun', valor: 6000 },
      { mes: 'Jul', valor: 6200 },
      { mes: 'Ago', valor: 6200 },
    ],
    comparativoSemanaAnterior: {
      funcionariosAtivos: 2,
      pedidosEnviados: 3,
      taxaResposta: 90,
    },
  },
  '6': {
    status: 'inativo',
    endereco: {
      cep: '05407-002',
      logradouro: 'Rua Cardeal Arcoverde',
      numero: '800',
      bairro: 'Pinheiros',
      cidade: 'São Paulo',
      uf: 'SP',
    },
    contrato: undefined,
    documentos: [],
    pausas: [{ id: 'p3', data: '2026-06-20', motivo: null }],
    funcionarios: [],
    envios: [
      {
        id: 'e8',
        data: '2026-05-04',
        horario: '11:30',
        status: 'erro',
        notaFiscalNumero: null,
        notaFiscalEmitidaEm: null,
        responsavel: 'Rafael Souza',
        motivoErro: 'Empresa sem contrato ativo na data',
      },
    ],
    respostasSemanais: [],
    faturamentoMensal: [
      { mes: 'Fev', valor: 3200 },
      { mes: 'Mar', valor: 2800 },
      { mes: 'Abr', valor: 1400 },
      { mes: 'Mai', valor: 0 },
    ],
  },
}
