import 'server-only'

import type { EmpresaDetail } from '../types'

export const EMPTY_DETAIL: EmpresaDetail = {
  status: 'ativo',
  endereco: {
    cep: '',
    logradouro: '',
    numero: '',
    bairro: '',
    cidade: '',
    uf: '',
  },
  pausas: [],
  funcionarios: [],
  envios: [],
  respostasSemanais: [],
  faturamentoMensal: [],
}

export const mockEmpresaDetails: Record<string, EmpresaDetail> = {
  '1': {
    status: 'ativo',
    endereco: {
      cep: '01310-200',
      logradouro: 'Avenida Paulista',
      numero: '1578',
      complemento: 'Andar 12',
      bairro: 'Bela Vista',
      cidade: 'São Paulo',
      uf: 'SP',
    },
    contrato: {
      valor: 18500,
      vigenciaInicio: '2026-01-01',
      vigenciaFim: '2026-12-31',
      prazoPagamento: 'Todo dia 10, mês seguinte',
      vigente: true,
    },
    pausas: [
      { id: 'p1', data: '2026-04-21', motivo: 'Feriado municipal' },
      { id: 'p2', data: '2026-06-04', motivo: 'Manutenção do refeitório' },
      { id: 'p4', data: '2026-09-07', motivo: 'Feriado nacional' },
    ],
    funcionarios: [
      {
        id: 'f1',
        nome: 'Ana Beatriz Ferreira',
        setor: 'Obras',
        turno: 'Almoço',
        modalidade: 'marmita',
        vinculoStatus: 'ativo',
        respondeuEstaSemana: true,
      },
      {
        id: 'f2',
        nome: 'Bruno Cesar Lima',
        setor: 'Obras',
        turno: 'Almoço',
        modalidade: 'marmita',
        vinculoStatus: 'ativo',
        respondeuEstaSemana: true,
      },
      {
        id: 'f3',
        nome: 'Camila Ribeiro Alves',
        setor: 'Administrativo',
        turno: 'Almoço',
        modalidade: 'marmita',
        vinculoStatus: 'ativo',
        respondeuEstaSemana: false,
      },
      {
        id: 'f4',
        nome: 'Diego Santos Pereira',
        setor: 'Administrativo',
        turno: 'Janta',
        modalidade: 'transport',
        vinculoStatus: 'inativo',
        respondeuEstaSemana: false,
      },
    ],
    envios: [
      {
        id: 'e1',
        data: '2026-07-27',
        status: 'confirmado',
        notaFiscalNumero: '000123',
        notaFiscalEmitidaEm: '2026-07-27',
      },
      {
        id: 'e2',
        data: '2026-07-28',
        status: 'confirmado',
        notaFiscalNumero: '000131',
        notaFiscalEmitidaEm: '2026-07-28',
      },
      {
        id: 'e3',
        data: '2026-07-29',
        status: 'erro',
        notaFiscalNumero: null,
        notaFiscalEmitidaEm: null,
      },
      {
        id: 'e4',
        data: '2026-07-30',
        status: 'confirmado',
        notaFiscalNumero: '000148',
        notaFiscalEmitidaEm: '2026-07-30',
      },
      {
        id: 'e5',
        data: '2026-07-31',
        status: 'enviado',
        notaFiscalNumero: null,
        notaFiscalEmitidaEm: null,
      },
    ],
    respostasSemanais: [
      { dia: 'Dom', responderam: 6, pendentes: 2 },
      { dia: 'Seg', responderam: 34, pendentes: 8 },
      { dia: 'Ter', responderam: 37, pendentes: 5 },
      { dia: 'Qua', responderam: 30, pendentes: 12 },
      { dia: 'Qui', responderam: 36, pendentes: 6 },
      { dia: 'Sex', responderam: 31, pendentes: 11 },
      { dia: 'Sáb', responderam: 9, pendentes: 3 },
    ],
    satisfacao: { media: 4.4, totalAvaliacoes: 87 },
    faturamentoMensal: [
      { mes: 'Mar', valor: 15200 },
      { mes: 'Abr', valor: 16800 },
      { mes: 'Mai', valor: 17650 },
      { mes: 'Jun', valor: 18100 },
      { mes: 'Jul', valor: 18500 },
      { mes: 'Ago', valor: 18500 },
    ],
    comparativoSemanaAnterior: {
      funcionariosAtivos: 3,
      pedidosEnviados: 4,
      taxaResposta: 74,
    },
  },
  '2': {
    status: 'ativo',
    endereco: {
      cep: '04543-000',
      logradouro: 'Rua Funchal',
      numero: '263',
      bairro: 'Vila Olímpia',
      cidade: 'São Paulo',
      uf: 'SP',
    },
    contrato: {
      valor: 6200,
      vigenciaInicio: '2026-03-02',
      vigenciaFim: '2027-03-01',
      prazoPagamento: 'Todo dia 5, mês seguinte',
      vigente: true,
    },
    pausas: [],
    funcionarios: [
      {
        id: 'f5',
        nome: 'Eduarda Martins Souza',
        setor: 'Desenvolvimento',
        turno: 'Almoço',
        modalidade: 'marmita',
        vinculoStatus: 'ativo',
        respondeuEstaSemana: true,
      },
      {
        id: 'f6',
        nome: 'Felipe Augusto Rocha',
        setor: 'Desenvolvimento',
        turno: 'Almoço',
        modalidade: 'marmita',
        vinculoStatus: 'ativo',
        respondeuEstaSemana: false,
      },
    ],
    envios: [
      {
        id: 'e6',
        data: '2026-07-29',
        status: 'confirmado',
        notaFiscalNumero: '000210',
        notaFiscalEmitidaEm: '2026-07-29',
      },
      {
        id: 'e7',
        data: '2026-07-30',
        status: 'confirmado',
        notaFiscalNumero: '000217',
        notaFiscalEmitidaEm: '2026-07-30',
      },
    ],
    respostasSemanais: [
      { dia: 'Dom', responderam: 1, pendentes: 0 },
      { dia: 'Seg', responderam: 8, pendentes: 1 },
      { dia: 'Ter', responderam: 9, pendentes: 0 },
      { dia: 'Qua', responderam: 7, pendentes: 2 },
      { dia: 'Qui', responderam: 9, pendentes: 0 },
      { dia: 'Sex', responderam: 6, pendentes: 3 },
      { dia: 'Sáb', responderam: 2, pendentes: 0 },
    ],
    satisfacao: { media: 4.7, totalAvaliacoes: 15 },
    faturamentoMensal: [
      { mes: 'Mai', valor: 5800 },
      { mes: 'Jun', valor: 6000 },
      { mes: 'Jul', valor: 6200 },
      { mes: 'Ago', valor: 6200 },
    ],
    comparativoSemanaAnterior: {
      funcionariosAtivos: 2,
      pedidosEnviados: 3,
      taxaResposta: 90,
    },
  },
  '6': {
    status: 'inativo',
    endereco: {
      cep: '05407-002',
      logradouro: 'Rua Cardeal Arcoverde',
      numero: '800',
      bairro: 'Pinheiros',
      cidade: 'São Paulo',
      uf: 'SP',
    },
    contrato: undefined,
    pausas: [{ id: 'p3', data: '2026-06-20', motivo: null }],
    funcionarios: [],
    envios: [
      {
        id: 'e8',
        data: '2026-05-04',
        status: 'erro',
        notaFiscalNumero: null,
        notaFiscalEmitidaEm: null,
      },
    ],
    respostasSemanais: [],
    faturamentoMensal: [
      { mes: 'Fev', valor: 3200 },
      { mes: 'Mar', valor: 2800 },
      { mes: 'Abr', valor: 1400 },
      { mes: 'Mai', valor: 0 },
    ],
  },
}
